INSERT INTO USER (USERNAME, PASSWORD) VALUES ('oaa', '$2a$10$n4mjtGI4lq303AZ93JEMc.vFfjL71QNuoK3DAYRDkokU8jdgTcGkW');
INSERT INTO "ROLE"(ROLE_NAME, ROLE_DESC)VALUES('admin', '管理员');
INSERT INTO "USER_ROLE"(USER_ID, ROLE_ID)VALUES(1, 1);