server:
  port: 9701
  servlet:
    context-path: /security
    session:
      timeout: 30m
    # 防止SpringSecurity设置编码为ISO-8859-1
    encoding:
      charset: utf-8
      force: on
      enabled: on

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: sa
    password: 123456
    url: jdbc:h2:mem:dbtest;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    platform: h2
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: classpath:mapper/**/*xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
  type-aliases-package: top.funsite.springboot.security.entity

jwt:
  token:
    subject: springboot
    expiration: 30m
    appSecretKey: security

logging:
  level: {top.funsite.springboot.security.mapper: debug}