server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: rootadmin
    url: jdbc:mysql://localhost:3306/springboot_exercises?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai

mybatis:
  mapper-locations: classpath:mapper/**/*xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

logging:
  level: {priv.lyq.springboot.security.mapper: debug}