server:
  port: 9703
  servlet:
    context-path: /web

spring:
  mvc:
    throw-exception-if-no-handler-found: on
  resources:
    add-mappings: off
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: rootadmin
    url: jdbc:mysql://localhost:3306/springboot_exercises?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver