databaseConfig:
  mybatis:
    configLocation: classpath:config/mybatis-configuration.xml
    mapperLocations: classpath:mapper/**/*.xml
  defaultDb: NARCOS_1
  datasource:
    NARCOS_1:
      url: jdbc:mysql://localhost:3306/springboot_exercises?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: rootadmin
    NARCOS_2:
      url: jdbc:mysql://localhost:3306/springboot_exercises2?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: rootadmin